name: Upload lets-talk to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - app/**
      - '!app/.packages/**'
      - .github/workflows/app-to-ft.yml
      - .github/workflows/upload_app.sh


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_TALK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Upload to FifthTry using fastn
        run: ./.github/workflows/upload_app.sh
