name: Create a new release of backend/talk.wasm

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release Tag'
        required: true
      productionRelease:
        type: boolean
        description: Mark release as production ready
jobs:
  release-main:
    name: Release from latest main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CARGO_TERM_COLOR: always
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_TALK_TEMPLATE }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: print rustc version
        run: rustc --version
      - name: cargo build wasm
        run: cargo build --release --target wasm32-unknown-unknown
      - name: print file info
        run: |
          file ./target/wasm32-unknown-unknown/release/talk.wasm
      - name: Optimize with wasm-opt
        run: |
          curl -L -o "binaryen-version_119-x86_64-linux.tar.gz" "https://github.com/WebAssembly/binaryen/releases/download/version_119/binaryen-version_119-x86_64-linux.tar.gz"
          tar -xzf binaryen-version_119-x86_64-linux.tar.gz
          mv binaryen-version_119/bin/wasm-opt .
          chmod +x wasm-opt
          ./wasm-opt -O3 ../target/wasm32-unknown-unknown/release/talk.wasm -o talk.wasm
          rm -rf binaryen-version_119 wasm-opt binaryen-version_119-aarch64-linux.tar.gz
      - name: print file info after optmization
        run: |
          file talk.wasm
          ls -lah talk.wasm
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Upload talk.wasm to lets-talk-template.fifthtry.site
        run: |
          fastn upload --file talk.wasm lets-talk-template
      - name: Update .github/RELEASE_TEMPLATE.md
        run: |
          sed -i "s/GITHUB_SHA/${GITHUB_SHA}/g" .github/RELEASE_TEMPLATE.md
          sed -i "s/DATE/$(date)/g" .github/RELEASE_TEMPLATE.md
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "talk.wasm"
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.releaseTag }}
          prerelease: ${{ github.event.inputs.productionRelease && github.event.inputs.productionRelease == 'false' }}
          bodyFile: .github/RELEASE_TEMPLATE.md
