name: Upload template to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - lets-talk-template.fifthtry.site/**
      - .github/workflows/template-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_TALK_TEMPLATE }}
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Upload lets-talk-template.fifthtry.site
        run: cd lets-talk-template.fifthtry.site/ && fastn upload lets-talk-template
