name: Upload template to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - template/**
      - '!template/.packages/**'
      - .github/workflows/template-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_TALK_TEMPLATE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Build the pages with fastn
        # TODO(siddhantk232): download a fresh copy of fifthtry-community/auth before uploading
        # TODO(siddhantk232): build a fresh copy of backend/ and put it in template/backend.wasm
        run: cd template/ && fastn upload lets-talk-template
